// ─────────────────────────────────────────────────────────────────────────
// CASE 002 — "The Last Message"
//
// This file is the single source of truth for the case. Nothing here is
// ever generated by an LLM. GROUND_TRUTH is never shown to the player
// directly except via the authored RevealScreen copy — it exists so the
// rest of the game (and, later, any LLM witness layer) has something fixed
// to stay consistent with.
// ─────────────────────────────────────────────────────────────────────────

import type { EvidenceFact, EvidenceId, EvidenceItem, RevelationDef, RevelationId, WitnessConfig } from "./types";

export const CASE_META = {
  title: "The Last Message",
  charge:
    "Elena Rossi, 34, is accused of murdering Daniel Costa, 37, her former partner.",
  victim: "Daniel Costa, 37",
  defendant: "Elena Rossi, 34",
  causeOfDeath: "Single stab wound to the chest.",
  prosecutionTheory: [
    "Elena and Daniel had been together for years.",
    "Daniel had moved on with Sofia.",
    "Elena was jealous and emotionally unstable.",
    "Elena went to Daniel's apartment and they argued.",
    "Daniel messaged Sofia: “She’s here. It’s getting ugly. I’ll call you when she leaves.”",
    "Elena's fingerprints are on the knife.",
    "Elena was present during the possible death window.",
    "Conclusion: Elena killed Daniel in a jealous rage.",
  ],
  defenceTheory: [
    "Elena was there; Elena and Daniel argued; Elena touched the knife — all true.",
    "But these true facts create a misleading story.",
    "Elena may not have been the last relevant person to see Daniel alive.",
  ],
};

/**
 * GROUND TRUTH — immutable. Never shown directly to the player until the
 * Reveal screen, and never fed to any witness as something they'd "know"
 * beyond their own individual slice below.
 */
export const GROUND_TRUTH = {
  relationshipTruth:
    "Daniel had been lying to both Elena and Sofia. He told Sofia that Elena was firmly in the past. He told Elena that things with Sofia were uncertain, and that perhaps he and Elena had ended things too quickly. He kept both relationships emotionally alive because he hated confrontation.",
  theNight:
    "Elena visited and left at 23:52 — Daniel alive, no stabbing. Sofia visited 23:53–23:57 — Daniel alive when she left. Tom returned 23:59–00:04 and argued with Daniel. During a physical struggle, Daniel — who had grabbed the kitchen knife himself while angrily gesturing and ordering Tom to leave — was accidentally stabbed in the chest as Tom tried to push past him. Tom did not intend to stab Daniel, panicked, and left without calling for help.",
  culpability:
    "Elena did not kill Daniel. Tom's legal responsibility is deliberately left open — accidental death during a struggle, reckless conduct, possible manslaughter, or failure to render aid are all live readings. But the stabbing was not an intentional attack by anyone, and it was not Elena.",
};

/** Canonical, ordered, never-changes timeline of the night. */
export const TIMELINE = [
  { time: "19:32", label: "Tom visits Daniel. They discuss Elena and Sofia." },
  { time: "20:07", label: "Tom leaves Daniel's apartment." },
  { time: "21:14", label: "Tom → Daniel (text): “You need to stop telling both of them different versions.”" },
  { time: "21:19", label: "Daniel → Tom: “I know.”" },
  { time: "21:21", label: "Tom → Daniel: “Then fix it tonight.”" },
  { time: "22:38", label: "Daniel and Elena speak by phone." },
  { time: "22:41", label: "Elena enters the building." },
  { time: "~22:45–23:00", label: "Elena and Daniel argue. Daniel admits part of the truth. Brief physical contact — Elena shoves Daniel's shoulder after he blocks her path. She does not stab him." },
  { time: "23:06", label: "Daniel → Sofia (text): “She's here. It's getting ugly. I'll call you when she leaves.”" },
  { time: "23:27", label: "Elena drafts but never sends: “You don't get to rewrite what happened.”" },
  { time: "23:34", label: "Daniel calls his brother Marco." },
  { time: "23:37", label: "Daniel → Tom (text): “You were right. This is a disaster.”" },
  { time: "23:46", label: "Elena → friend (text): “I'm leaving. I'm done with this.”" },
  { time: "23:48", label: "Sofia calls Daniel. No answer." },
  { time: "23:50", label: "Daniel calls Sofia back. Connected 36 seconds: “Elena's leaving. I need you to come here. There's something I should have told you months ago.”" },
  { time: "23:52", label: "Elena leaves the building. Daniel is alive." },
  { time: "23:53", label: "Sofia enters through the underground garage." },
  { time: "23:54", label: "Lift takes Sofia to Daniel's floor." },
  { time: "~23:54–23:57", label: "Daniel tells Sofia the truth — Elena was never really finished, he kept both of them going. Sofia becomes furious, shouts, grabs his shirt, throws his phone onto the sofa." },
  { time: "23:57", label: "Sofia takes the lift back down. Daniel is alive." },
  { time: "23:58", label: "Daniel's phone is unlocked for ~20 seconds. He is alive — though this alone isn't something an investigator could prove from the record itself; see E05." },
  { time: "23:59", label: "Tom enters through the underground parking." },
  { time: "00:00", label: "Tom takes the lift to Daniel's floor. They argue — Daniel accuses Tom of interfering and making things worse." },
  { time: "~00:00–00:02", label: "Daniel shoves Tom; Tom shoves back. Daniel grabs the kitchen knife while angrily gesturing and orders Tom to leave. Tom tries to push past. During the struggle, Daniel — still holding the knife — is accidentally stabbed in the chest." },
  { time: "~00:02", label: "Tom panics and leaves without calling for help." },
  { time: "00:03", label: "Tom calls Daniel again. No answer." },
  { time: "00:04", label: "Lift returns Tom to the garage." },
  { time: "00:05", label: "Tom's vehicle exits the garage." },
  { time: "00:17", label: "Emergency services arrive." },
];

// ───────────────────────────── Evidence ─────────────────────────────────

export const EVIDENCE: EvidenceItem[] = [
  {
    id: "E01_knife",
    title: "Kitchen knife",
    category: "physical",
    summary: "Found near Daniel. Fingerprint analysis complete.",
    details: [
      "Kitchen knife recovered at the scene, found near Daniel's body.",
      "Fingerprints identified: Elena Rossi, Daniel Costa.",
      "No third identifiable fingerprints on the blade or handle.",
    ],
    initial: true,
  },
  {
    id: "E02_msg_sofia_2306",
    title: "Text to Sofia, 23:06",
    category: "message",
    summary: "Daniel messages Sofia while Elena is still there.",
    details: [
      "Daniel Costa → Sofia Mendes — 23:06",
      "“She’s here. It’s getting ugly. I’ll call you when she leaves.”",
    ],
    initial: true,
  },
  {
    id: "E03_entrance_camera",
    title: "Building entrance camera",
    category: "video",
    summary: "Front door footage — does not cover the underground garage.",
    details: [
      "22:41 — Elena Rossi enters.",
      "23:52 — Elena Rossi leaves.",
      "23:58 — Someone leaves through the front entrance; image is unclear and unidentified.",
      "00:17 — Emergency services arrive.",
      "Note: the underground garage entrance is NOT covered by this camera.",
    ],
    initial: true,
  },
  {
    id: "E04_forensic_prelim",
    title: "Preliminary forensic report",
    category: "forensic",
    summary: "Estimated death window, wound type, and absence of defensive wounds.",
    details: [
      "Probable time of death: between 23:30 and 00:10.",
      "Cause of death: single stab wound to the chest.",
      "Daniel likely survived for several minutes after being wounded, and moved a short distance.",
      "No obvious defensive wounds on the body.",
    ],
    initial: true,
  },
  {
    id: "E05_daniel_phone_records",
    title: "Daniel's phone records",
    category: "records",
    summary: "Full call and message log for the night, requested from the carrier.",
    details: [
      "22:38 — Call with Elena Rossi.",
      "23:06 — Text to Sofia Mendes: “She's here. It's getting ugly. I'll call you when she leaves.”",
      "23:34 — Call with Marco Costa (brother).",
      "23:48 — Missed call from Sofia Mendes.",
      "23:50 — Call to Sofia Mendes, connected, 36 seconds.",
      "23:53 — Text from Sofia Mendes: “I'm coming up.”",
      "23:58 — Phone unlocked, active for approximately 20 seconds.",
      "00:03 — Missed call from Tom Becker.",
    ],
    initial: false,
  },
  {
    id: "E06_elena_phone_records",
    title: "Elena's phone records",
    category: "records",
    summary: "Full call and message log for the night.",
    details: [
      "23:27 — Unsent draft message: “You don't get to rewrite what happened.”",
      "23:46 — Text to a friend: “I'm leaving. I'm done with this.”",
      "23:52 — Leaves the building (corroborated by E03).",
      "23:56 — Phone activity consistent with movement away from the building.",
      "00:01 — Four-minute call with a friend.",
      "00:08 — Text to the same friend: “I can't believe I let him drag me back into this.”",
    ],
    initial: false,
  },
  {
    id: "E07_tom_phone_records",
    title: "Tom's phone records",
    category: "records",
    summary: "Full call and message log for the night.",
    details: [
      "23:37 — Text from Daniel: “You were right. This is a disaster.”",
      "23:49 — Phone disconnects from home Wi-Fi.",
      "23:56 — Phone location consistent with Daniel's neighbourhood.",
      "00:03 — Call to Daniel, unanswered.",
      "00:07 — Phone location shows movement away from the building.",
      "00:11 — Text to Daniel: “Call me when you calm down.”",
    ],
    initial: false,
  },
  {
    id: "E08_garage_access_log",
    title: "Underground garage access log",
    category: "records",
    summary: "Key-fob and lift records for the garage entrance — not covered by the front camera.",
    details: [
      "23:53 — Sofia Mendes enters via the garage.",
      "23:54 — Lift called to Daniel's floor.",
      "23:57 — Lift called back down to parking.",
      "23:59 — Tom Becker enters via the garage.",
      "00:00 — Lift called to Daniel's floor.",
      "00:04 — Lift called back down to parking.",
      "00:05 — Tom Becker's vehicle exits the garage.",
    ],
    initial: false,
  },
];

/**
 * Hand-authored breakdown of what each document actually establishes, for
 * the case board. Deliberately NOT a mechanical dump of every detail
 * line — a curated reading, the same editorial judgment an investigator
 * writing up a document would apply. Each entry states its own time (if
 * any), its content, and its epistemic type; "lead" is used where the
 * record itself is ambiguous (e.g. an unidentified figure on camera).
 */
export const EVIDENCE_FACTS: Record<EvidenceId, EvidenceFact[]> = {
  E01_knife: [
    { content: "Kitchen knife recovered near Daniel's body.", type: "fact" },
    { content: "Fingerprints on the knife: Elena Rossi and Daniel Costa only — no third identifiable print.", type: "fact" },
  ],
  E02_msg_sofia_2306: [
    { time: "23:06", content: "Daniel texts Sofia: “She's here. It's getting ugly. I'll call you when she leaves.”", type: "fact" },
  ],
  E03_entrance_camera: [
    { time: "22:41", content: "Elena enters through the front entrance.", type: "fact" },
    { time: "23:52", content: "Elena leaves through the front entrance.", type: "fact" },
    { time: "23:58", content: "Someone leaves through the front entrance; the image is unclear and unidentified.", type: "lead" },
    { content: "The underground garage entrance is not covered by this camera.", type: "fact" },
  ],
  E04_forensic_prelim: [
    { content: "Probable time of death: between 23:30 and 00:10.", type: "fact" },
    { content: "Cause of death: a single stab wound to the chest.", type: "fact" },
    { content: "No obvious defensive wounds on the body.", type: "fact" },
  ],
  E05_daniel_phone_records: [
    { time: "23:34", content: "Daniel calls his brother Marco.", type: "fact" },
    { time: "23:50", content: "Daniel calls Sofia back — connected for 36 seconds.", type: "fact" },
    { time: "23:58", content: "Daniel's phone is unlocked and active for approximately 20 seconds. This record does not establish who used it.", type: "fact" },
    { time: "00:03", content: "A missed call from Tom Becker.", type: "fact" },
  ],
  E06_elena_phone_records: [
    { time: "23:27", content: "Elena drafts but never sends: “You don't get to rewrite what happened.”", type: "fact" },
    { time: "23:46", content: "Elena texts a friend: “I'm leaving. I'm done with this.”", type: "fact" },
    { time: "00:01", content: "Elena has a four-minute call with a friend, after the building.", type: "fact" },
  ],
  E07_tom_phone_records: [
    { time: "23:49", content: "Tom's phone disconnects from his home Wi-Fi.", type: "lead" },
    { time: "23:56", content: "Tom's phone location is consistent with Daniel's neighbourhood.", type: "fact" },
    { time: "00:03", content: "Tom calls Daniel — unanswered.", type: "fact" },
  ],
  E08_garage_access_log: [
    { time: "23:53", content: "Sofia Mendes enters via the underground garage.", type: "fact" },
    { time: "23:59", content: "Tom Becker enters via the underground garage.", type: "fact" },
    { time: "00:05", content: "Tom Becker's vehicle exits the garage.", type: "fact" },
  ],
};

// ───────────────────────────── Witnesses ─────────────────────────────────

export const WITNESSES: WitnessConfig[] = [
  // ───────────────────────────── ELENA ─────────────────────────────
  {
    id: "elena",
    name: "Elena Rossi",
    role: "The defendant — Daniel's former partner",
    age: 34,
    context:
      "Together with Daniel ~6 years. He called it a breakup 8 months ago — Elena says it was never that clean. She admits being there that night. She denies killing him.",
    keyFacts: [
      "Together with Daniel for ~6 years",
      "Admits visiting that night, and touching the knife earlier",
      "Denies killing him",
    ],
    portraitPrompt:
      "Black woman, mid-30s, tired and guarded expression, cinematic dark lighting",
    portraitImage: "/portraits/elena.jpg",
    accentColor: "#c084fc",
    baselineDemeanor: "guarded",
    deflections: [
      "I've already told you what happened. I didn't kill him.",
      "I know how this looks. I know. But that's not what happened.",
      "Ask me something else. I don't know what you want me to say.",
    ],
    demeanorImages: {
      guarded: "/portraits/elena.jpg",
      defensive: "/portraits/elena_defensive.jpg",
      composed: "/portraits/elena_composed.jpg",
      shaken: "/portraits/elena_shaken.jpg",
    },
    demeanorLines: {
      guarded: "She watches you carefully, measuring every question before she answers.",
      defensive: "Her arms are crossed. She's decided you're not on her side.",
      composed: "She's steadier now — still careful, but no longer bracing for a fight.",
      shaken: "Something just cracked her composure. She didn't see that coming.",
    },
    topics: [
      {
        id: "relationship",
        chipLabel: "What was your relationship with Daniel?",
        tone: "neutral",
        keywords: ["relationship", "together", "breakup", "broke up", "dating", "together six years", "exes", "ex", "past"],
        stages: [
          {
            text: "We were together almost six years. He called it a breakup eight months ago, but it was never clean — we kept talking, kept meeting. We slept together more than once after he supposedly ended it. He'd tell me things with Sofia were uncertain, that maybe we'd ended too fast. I believed him, more fool me.",
            demeanor: "guarded",
            addsBoardEntries: [
              { type: "claim", text: "Elena: the “breakup” eight months ago was never clean — she and Daniel stayed involved.", source: "elena" },
            ],
          },
        ],
      },
      {
        id: "that_night",
        chipLabel: "Why did you go there that night?",
        tone: "soft",
        keywords: ["that night", "why did you go", "visit", "called you", "invited"],
        stages: [
          {
            text: "He called me around 10:40. He sounded strange — said he needed to “tell me the truth.” I went over. I got there a little after that.",
            demeanor: "guarded",
            addsBoardEntries: [
              { type: "claim", text: "Elena: Daniel called her and said he needed to “tell her the truth” before she came over.", source: "elena", timestamp: "22:38" },
            ],
          },
        ],
      },
      {
        id: "argument",
        chipLabel: "What really happened once that argument turned physical?",
        tone: "accusative",
        keywords: ["argument", "argue", "fight", "contact", "physical", "touch", "push", "shove", "hit"],
        stages: [
          {
            text: "We argued. He admitted some of it — that he'd been telling Sofia I was ancient history while telling me the opposite. I was angry. There might have been some contact, nothing serious.",
            demeanor: "defensive",
          },
          {
            text: "Fine — I shoved him. He blocked the doorway when I tried to leave and I shoved his shoulder to get past. That's it. That's all it was. I did not pick up a knife and I did not stab him.",
            minAskCount: 2,
            demeanor: "defensive",
            addsBoardEntries: [
              { type: "claim", text: "Elena admits: she shoved Daniel's shoulder when he blocked her path. Denies anything further.", source: "elena" },
            ],
          },
        ],
      },
      {
        id: "knife",
        chipLabel: "Why are your prints on the murder weapon, Elena?",
        tone: "accusative",
        keywords: ["knife", "prints", "fingerprint"],
        stages: [
          {
            text: "I used it earlier — cutting lime for a drink, I think. Before things got bad. I didn't touch it again after that.",
            requiresEvidence: ["E01_knife"],
            demeanor: "guarded",
            addsBoardEntries: [
              { type: "claim", text: "Elena: touched the knife earlier in the evening for an unrelated reason, before the argument escalated.", source: "elena" },
            ],
          },
        ],
      },
      {
        id: "leaving",
        chipLabel: "What time did you leave?",
        tone: "soft",
        keywords: ["leave", "left", "when did you go", "what time"],
        stages: [
          {
            text: "I left before midnight. He was alive — angry, upset, but alive and standing in his kitchen when I walked out. I went straight home.",
            demeanor: "composed",
            addsBoardEntries: [
              { type: "claim", text: "Elena: left before midnight, Daniel alive and standing when she left.", source: "elena", timestamp: "23:52" },
            ],
          },
        ],
      },
      {
        id: "sofia_tom_after",
        chipLabel: "Did you see Sofia or Tom that night?",
        tone: "neutral",
        keywords: ["sofia", "tom", "see anyone", "after you left"],
        stages: [
          {
            text: "No. I have no idea what happened after I left. I didn't see either of them.",
            demeanor: "composed",
          },
        ],
      },
    ],
    reactions: {
      tom_returned: {
        text: "What? No — I had no idea anyone else went back there. I just left. I thought that was the end of it for the night. If someone else was there after me, that's... that changes things, doesn't it?",
        demeanor: "shaken",
        addsBoardEntries: [
          { type: "claim", text: "Elena, told Tom also returned that night: genuinely surprised, had no knowledge of it.", source: "elena" },
        ],
      },
      sofia_visited: {
        text: "Sofia was there too? After I'd gone? ...I didn't know that. God, if Daniel told her what he told me — if he finally said it to both of us the same night — no wonder everything happened the way it did.",
        demeanor: "shaken",
        addsBoardEntries: [
          { type: "claim", text: "Elena, told Sofia also visited that night: surprised, starts connecting it to what Daniel admitted to her.", source: "elena" },
        ],
      },
    },
  },

  // ───────────────────────────── SOFIA ─────────────────────────────
  {
    id: "sofia",
    name: "Sofia Mendes",
    role: "Daniel's girlfriend — together ~5 months",
    context:
      "Dating Daniel ~5 months. He told her Elena was long in the past. She first claims no contact with Daniel after his 23:06 text.",
    keyFacts: [
      "Dating Daniel for ~5 months",
      "Told Elena was firmly “in the past”",
      "Initially denies any later contact that night",
    ],
    portraitPrompt:
      "South Asian woman, late 20s, composed but tense expression, cinematic dark lighting",
    portraitImage: "/portraits/sofia.jpg",
    accentColor: "#f472b6",
    baselineDemeanor: "composed",
    freeformEnabled: true,
    deflections: [
      "I've told you everything I know.",
      "I don't see why that matters.",
      "I really don't think I can help you with that.",
    ],
    defensiveLines: [
      "I don't know what you want me to say. I've told you what happened.",
      "That's not fair — I came here and told you the truth once I could.",
      "I'm not going to just agree with a version of events I don't recognize.",
    ],
    demeanorImages: {
      composed: "/portraits/sofia.jpg",
      defensive: "/portraits/sofia_defensive.jpg",
      nervous: "/portraits/sofia_nervous.jpg",
      shaken: "/portraits/sofia_shaken.jpg",
    },
    demeanorLines: {
      composed: "She holds herself together — poised, but watching you closely.",
      defensive: "Caught in something. Her voice has gone clipped and careful.",
      nervous: "Her hands won't quite settle. She's deciding how much to say.",
      shaken: "Whatever you just told her landed hard.",
    },
    topics: [
      {
        id: "relationship",
        chipLabel: "What did Daniel tell you about Elena?",
        tone: "neutral",
        keywords: ["elena", "relationship", "told you about", "ex"],
        stages: [
          {
            text: "He told me they'd broken up three months before we got together, and that Elena was having trouble accepting it — that she was unstable, honestly. I believed him.",
            demeanor: "composed",
            addsBoardEntries: [
              { type: "claim", text: "Sofia: Daniel told her Elena was firmly in the past and “unstable.”", source: "sofia" },
            ],
          },
        ],
      },
      {
        id: "contact_after_text",
        chipLabel: "Are you sure Daniel never contacted you again that night?",
        tone: "accusative",
        keywords: ["after", "call", "contact", "that night", "later", "23:06", "text"],
        stages: [
          {
            text: "No. That text at 23:06 was the last I heard from him that night.",
            demeanor: "composed",
          },
          {
            text: "...He called me back. Fine. At 23:50. We spoke for maybe half a minute. He said Elena was leaving, and that there was something he should have told me months ago.",
            presentedText: "...Fine — I can see you've got his phone records. He called me back. At 23:50. We spoke for maybe half a minute. He said Elena was leaving, and that there was something he should have told me months ago.",
            requiresEvidence: ["E05_daniel_phone_records"],
            demeanor: "defensive",
            addsBoardEntries: [
              { type: "contradiction", text: "Sofia initially denied any contact after 23:06 — phone records show a 36-second call at 23:50.", source: "sofia", timestamp: "23:50" },
            ],
          },
        ],
      },
      {
        id: "went_to_apartment",
        chipLabel: "Did you go to the apartment that night?",
        tone: "accusative",
        keywords: ["go to the apartment", "were you there", "visit", "garage"],
        stages: [
          {
            text: "No, I was home all night.",
            demeanor: "defensive",
          },
          {
            text: "...Yes. I went over. I came up through the garage — I didn't want to run into Elena on her way out.",
            presentedText: "...The garage log. Right. Yes — I went over. I came up through the garage, I didn't want to run into Elena on her way out.",
            requiresEvidence: ["E08_garage_access_log"],
            // Alternate route: she doesn't need to be confronted with the
            // garage log at all if she's already learned Tom went back
            // too and the player meets that with genuine understanding —
            // the thing she was protecting ("I might be the last one who
            // saw him") is no longer true, so admitting her own visit
            // stops costing her as much.
            altUnlock: { requiresRelayed: ["tom_returned"], requiresIntent: ["empathetic_appeal"] },
            altUnlockText:
              "...Can I tell you something? I've been so afraid of being the last person who saw him. If Tom went back after me, then — okay. Yes. I went over that night. I came up through the garage, because I didn't want to run into Elena.",
            demeanor: "nervous",
            addsBoardEntries: [
              { type: "claim", text: "Sofia admits she went to the apartment that night, entering via the underground garage.", source: "sofia", timestamp: "23:53" },
            ],
          },
        ],
      },
      {
        id: "what_happened_there",
        chipLabel: "What actually happened once you got up there?",
        tone: "accusative",
        keywords: ["happened", "what did he say", "angry", "fight", "shirt", "grab"],
        stages: [
          {
            text: "We talked.",
            requiresWitnessStage: { witness: "sofia", topic: "went_to_apartment", minStage: 1 },
            demeanor: "nervous",
          },
          {
            text: "He told me the truth — that he and Elena never really stopped, that he'd been lying to both of us. I was furious. I grabbed his shirt, I think I threw his phone onto the sofa. I shouted at him. Then I left. He was fine — upset, but fine, standing right there when I walked out.",
            requiresWitnessStage: { witness: "sofia", topic: "went_to_apartment", minStage: 1 },
            minAskCount: 2,
            demeanor: "shaken",
            addsBoardEntries: [
              { type: "claim", text: "Sofia: Daniel admitted the truth about Elena; Sofia got physical (grabbed his shirt) but left him alive and standing at 23:57.", source: "sofia", timestamp: "23:57" },
            ],
          },
        ],
      },
    ],
    reactions: {
      tom_returned: {
        text: "Tom? He went back? ...I didn't know that. I swear, when I left, Daniel was fine — upset, but fine. If Tom went up there after me, I have no idea what happened once I was gone.",
        demeanor: "shaken",
        addsBoardEntries: [
          { type: "claim", text: "Sofia, told Tom also returned that night: genuinely surprised, reaffirms Daniel was alive and fine when she left.", source: "sofia" },
        ],
      },
      daniel_lied_to_both: {
        text: "...So even his own brother knew. Great. That makes two people who could've warned me before I wasted five months on him.",
        demeanor: "shaken",
        addsBoardEntries: [
          { type: "claim", text: "Sofia, told Marco already knew Daniel was lying to both women: bitter, feels like she was the only one left in the dark.", source: "sofia" },
        ],
      },
    },
  },

  // ───────────────────────────── TOM ─────────────────────────────
  {
    id: "tom",
    name: "Tom Becker",
    role: "Daniel's close friend — ~9 years",
    context:
      "Daniel's friend of ~9 years. Repeatedly warned him he was stringing both women along. Claims he went home early that night.",
    keyFacts: [
      "Daniel's close friend for ~9 years",
      "Warned Daniel to stop lying to both women",
      "Initially claims he went straight home that night",
    ],
    portraitPrompt:
      "White man, mid-30s, uneasy and guarded expression, cinematic dark lighting",
    portraitImage: "/portraits/tom.jpg",
    accentColor: "#60a5fa",
    baselineDemeanor: "guarded",
    freeformEnabled: true,
    deflections: [
      "I already told you — I went home.",
      "I don't know what else you want from me.",
      "Why does that matter?",
    ],
    defensiveLines: [
      "I didn't do anything. I don't know why you're coming at me like this.",
      "That's not fair. You're putting words in my mouth.",
      "I've told you what I know. I'm not going to just agree with whatever you throw at me.",
    ],
    demeanorImages: {
      guarded: "/portraits/tom.jpg",
      defensive: "/portraits/tom_defensive.jpg",
      nervous: "/portraits/tom_nervous.jpg",
      panicking: "/portraits/tom_panicking.jpg",
      resigned: "/portraits/tom_resigned.jpg",
    },
    demeanorLines: {
      guarded: "He's giving short answers, arms crossed, waiting to see where this goes.",
      defensive: "He's decided this is an attack, and he's not giving any ground.",
      nervous: "There's sweat on his brow now. He knows you're getting closer.",
      panicking: "He's not composed anymore. Whatever's coming, he's bracing for it.",
      resigned: "The fight's gone out of him. He's just telling you the truth now.",
    },
    topics: [
      {
        id: "earlier_visit",
        chipLabel: "What did you talk about earlier that evening?",
        tone: "neutral",
        keywords: ["earlier", "visit", "talk about", "7pm", "19:32", "warn"],
        stages: [
          {
            text: "I went over around 7:30. I told him — again — that he needed to stop giving Elena and Sofia two different stories. He said he knew. I told him to fix it that night, one way or another.",
            demeanor: "guarded",
            addsBoardEntries: [
              { type: "claim", text: "Tom: warned Daniel earlier that evening to stop lying to both women and “fix it tonight.”", source: "tom", timestamp: "19:32" },
            ],
          },
        ],
      },
      {
        id: "after_that",
        chipLabel: "Where did you really go after you left, Tom?",
        tone: "accusative",
        keywords: ["after", "went home", "later that night", "where were you", "midnight"],
        stages: [
          {
            text: "I went home. I didn't go back.",
            demeanor: "guarded",
          },
          {
            text: "...Alright. I went back. Around midnight. I was worried about how the night was going to go.",
            presentedText: "...Alright. Fine — your phone records put me there, I know. I went back. Around midnight. I was worried about how the night was going to go.",
            requiresEvidence: ["E07_tom_phone_records"],
            demeanor: "defensive",
            addsBoardEntries: [
              { type: "contradiction", text: "Tom initially claimed he went straight home — phone and garage records show he returned around midnight.", source: "tom", timestamp: "23:59" },
            ],
          },
        ],
      },
      {
        id: "saw_sofia",
        chipLabel: "Did you see anyone when you got there?",
        tone: "soft",
        keywords: ["see anyone", "sofia", "saw someone", "garage"],
        stages: [
          {
            text: "I don't remember.",
            requiresWitnessStage: { witness: "tom", topic: "after_that", minStage: 1 },
            demeanor: "defensive",
          },
          {
            text: "I saw Sofia leaving as I was coming in through the garage. We didn't really speak.",
            requiresWitnessStage: { witness: "tom", topic: "after_that", minStage: 1 },
            requiresEvidence: ["E08_garage_access_log"],
            demeanor: "nervous",
            addsBoardEntries: [
              { type: "claim", text: "Tom admits he saw Sofia leaving as he entered the garage around midnight.", source: "tom", timestamp: "23:59" },
            ],
          },
        ],
      },
      {
        id: "went_up",
        chipLabel: "Did you go up to his apartment?",
        tone: "neutral",
        keywords: ["go up", "apartment", "floor", "lift", "elevator"],
        stages: [
          {
            text: "I needed to talk to him. Yes, I went up.",
            requiresWitnessStage: { witness: "tom", topic: "after_that", minStage: 1 },
            demeanor: "nervous",
            addsBoardEntries: [
              { type: "claim", text: "Tom admits he went up to Daniel's apartment after returning that night.", source: "tom", timestamp: "00:00" },
            ],
          },
        ],
      },
      {
        id: "the_argument",
        chipLabel: "What really happened between you two up there?",
        tone: "accusative",
        keywords: ["argument", "fight", "argue", "shove", "happened between"],
        stages: [
          {
            text: "We argued. He said I'd made things worse by interfering, by talking to both of them. It got heated. I shoved him, he shoved me back.",
            requiresWitnessStage: { witness: "tom", topic: "after_that", minStage: 1 },
            minAskCount: 1,
            demeanor: "defensive",
            addsBoardEntries: [
              { type: "claim", text: "Tom admits a physical shoving match with Daniel over Tom “interfering.”", source: "tom" },
            ],
          },
        ],
      },
      {
        id: "the_knife",
        chipLabel: "Did you kill him, Tom?",
        tone: "accusative",
        keywords: ["knife", "stab", "kill", "truth", "what really happened", "weapon"],
        stages: [
          {
            text: "I don't know what you're asking me.",
            requiresWitnessStage: { witness: "tom", topic: "the_argument", minStage: 0 },
            demeanor: "nervous",
          },
          {
            text: "He grabbed the knife off the counter — he was pointing at me with it, shouting at me to get out. I tried to push past him, get the door. We were tangled up for a second and… he had the knife. It went into him. I didn't stab him. I didn't touch that knife. I swear to you, I didn't mean for any of it.",
            presentedText: "...You already know, don't you — the forensic report, the knife. Fine. He grabbed the knife off the counter — he was pointing at me with it, shouting at me to get out. I tried to push past him, get the door. We were tangled up for a second and… he had the knife. It went into him. I didn't stab him. I swear to you, I didn't mean for any of it.",
            requiresWitnessStage: { witness: "tom", topic: "the_argument", minStage: 0 },
            requiresEvidence: ["E01_knife", "E04_forensic_prelim"],
            minAskCount: 1,
            // Alternate route: learning Sofia was ALSO there that night,
            // and that her account doesn't contradict his, makes him feel
            // less like the sole, isolated suspect — enough to volunteer
            // this without ever being confronted with the forensic report.
            altUnlock: { requiresRelayed: ["sofia_visited"], requiresIntent: ["empathetic_appeal"] },
            altUnlockText:
              "...Okay. Okay — you're going to find out one way or another, and I'd rather you heard it from me than pieced it together. He grabbed the knife off the counter, pointing it at me, shouting at me to get out. I tried to push past him. We were tangled up for a second and he had the knife, and it went into him. I didn't stab him. I swear to you, I didn't mean for any of it.",
            demeanor: "panicking",
            addsBoardEntries: [
              { type: "claim", text: "Tom's account: Daniel grabbed the knife himself; it entered him accidentally during the struggle as Tom tried to get past him.", source: "tom", timestamp: "~00:02" },
            ],
          },
          {
            text: "I already told you what happened. I panicked. I left. I should have called someone — I know that. I think about it every day.",
            requiresWitnessStage: { witness: "tom", topic: "the_argument", minStage: 0 },
            requiresEvidence: ["E01_knife", "E04_forensic_prelim"],
            minAskCount: 2,
            demeanor: "resigned",
          },
        ],
      },
      {
        id: "why_no_help",
        chipLabel: "Why didn't you call for help?",
        tone: "soft",
        keywords: ["help", "ambulance", "emergency", "call someone", "why didn't you"],
        stages: [
          {
            text: "I panicked. I know how that sounds. I know I should have. I've never been more scared in my life and I ran, and I will regret that forever.",
            requiresWitnessStage: { witness: "tom", topic: "the_knife", minStage: 1 },
            demeanor: "resigned",
          },
        ],
      },
    ],
    reactions: {
      sofia_contact_hidden: {
        text: "She lied too? ...Doesn't surprise me, honestly. Seems like everyone was keeping something back that night. Myself included, I suppose.",
        demeanor: "resigned",
        addsBoardEntries: [
          { type: "claim", text: "Tom, told Sofia also hid something that night: unsurprised, draws a parallel to his own lie.", source: "tom" },
        ],
      },
      // New this round: he already privately knew Sofia had been there
      // (he saw her leaving via the garage — his own saw_sofia topic) —
      // this isn't new canon, just his first acknowledgment that it's now
      // something the Judge actually knows too, not just him.
      sofia_visited: {
        text: "Yeah. I saw her leaving when I came in. I didn't say anything earlier because I didn't want to be the one who put her in this, on top of everything else.",
        generative: true,
        demeanor: "nervous",
        addsBoardEntries: [
          { type: "claim", text: "Tom, told Sofia's visit is now known: confirms he saw her leaving as he arrived, says he withheld it to avoid implicating her.", source: "tom" },
        ],
      },
    },
  },

  // ───────────────────────────── MARCO ─────────────────────────────
  {
    id: "marco",
    name: "Marco Costa",
    role: "Daniel's older brother",
    context:
      "Knew Daniel better than anyone — a man who hated confrontation and kept both women on the line rather than face either honestly. Spoke to him that night.",
    keyFacts: [
      "Daniel's older brother",
      "Knew Daniel avoided confrontation at all costs",
      "Spoke to Daniel by phone the night he died",
    ],
    portraitPrompt:
      "Middle Eastern man, early 40s, grieving but composed, cinematic dark lighting",
    portraitImage: "/portraits/marco.jpg",
    accentColor: "#fbbf24",
    baselineDemeanor: "composed",
    deflections: [
      "I wasn't there. I can only tell you what I know about my brother.",
      "I've told you what I know.",
    ],
    demeanorImages: {
      composed: "/portraits/marco.jpg",
      shaken: "/portraits/marco_shaken.jpg",
    },
    demeanorLines: {
      composed: "Steady, measured — a man used to holding himself together.",
      shaken: "This has gotten through to him. The composure is gone.",
    },
    topics: [
      {
        id: "daniels_personality",
        chipLabel: "What was Daniel like?",
        tone: "soft",
        keywords: ["personality", "like", "character", "daniel was"],
        stages: [
          {
            text: "Daniel hated confrontation more than almost anyone I've known. If telling someone the truth meant a fight, he'd rather tell them whatever kept the peace — even if it meant two completely different stories to two different people. It wasn't cruelty. It was cowardice, mostly.",
            demeanor: "composed",
            addsBoardEntries: [
              { type: "claim", text: "Marco: Daniel habitually avoided confrontation by telling people whatever kept the peace.", source: "marco" },
            ],
          },
        ],
      },
      {
        id: "the_lies",
        chipLabel: "Did Daniel ever talk to you about Elena and Sofia?",
        tone: "neutral",
        keywords: ["elena", "sofia", "both of them", "lied", "lying"],
        stages: [
          {
            text: "About a week before he died he called me, sounding rattled. He said, ‘I've lied to both of them.’ I didn't push for details — I assumed it would sort itself out, the way it always did with him.",
            demeanor: "composed",
            addsBoardEntries: [
              { type: "claim", text: "Marco: Daniel told him “I've lied to both of them” about a week before he died.", source: "marco" },
            ],
          },
        ],
      },
      {
        id: "that_night_call",
        chipLabel: "Did you speak to Daniel that night?",
        tone: "neutral",
        keywords: ["that night", "call", "phone", "speak to him", "23:34", "talked to", "spoke", "did you talk"],
        stages: [
          {
            text: "Briefly, yes. He called me — I don't remember exactly when. He sounded stressed.",
            demeanor: "composed",
          },
          {
            text: "He called me around 11:30. He sounded stressed — said something like ‘I have to stop lying to people tonight.’ I told him to just talk to them calmly. I had no idea it was that night, with Elena right there.",
            presentedText: "...His phone records, right. Yes — he called me at 23:34. He sounded stressed, said something like ‘I have to stop lying to people tonight.’ I told him to just talk to them calmly. I had no idea it was that night, with Elena right there.",
            requiresEvidence: ["E05_daniel_phone_records"],
            demeanor: "composed",
            addsBoardEntries: [
              { type: "claim", text: "Marco: Daniel called him at 23:34, stressed, saying he had to “stop lying to people tonight.”", source: "marco", timestamp: "23:34" },
            ],
          },
        ],
      },
    ],
    reactions: {
      tom_confessed: {
        text: "Tom... he was practically family to us. If that's true — if it was an accident — God. I don't know what to do with that. But it doesn't surprise me that Daniel grabbed a knife mid-argument. He always had to be holding something when he felt cornered. Never knew what to do with his hands when he was scared.",
        demeanor: "shaken",
        addsBoardEntries: [
          { type: "claim", text: "Marco, told Tom's account: devastated but not surprised Daniel would grab something when cornered in an argument.", source: "marco" },
        ],
      },
      elena_shoved: {
        text: "She put her hands on him? ...That doesn't shock me, if I'm honest. Things always got loud when those two were in a room together. Doesn't mean she did anything more than that.",
        demeanor: "composed",
        addsBoardEntries: [
          { type: "claim", text: "Marco, told Elena admitted shoving Daniel: unsurprised given their history, but doesn't read more into it.", source: "marco" },
        ],
      },
    },
  },

  // ───────────────────────────── JULIA ─────────────────────────────
  {
    id: "julia",
    name: "Julia Ferrer",
    role: "Neighbour, lives across the hall",
    context:
      "Heard fragments of arguments through the wall. Her account is honest but imprecise — she didn't see everything clearly.",
    keyFacts: [
      "Lives across the hall from Daniel",
      "Heard raised voices and doors that night",
      "Saw someone leave — but her account is imprecise",
    ],
    portraitPrompt:
      "East Asian woman, 60s, curious and talkative expression, standing in an apartment hallway, cinematic dark lighting",
    portraitImage: "/portraits/julia.jpg",
    accentColor: "#34d399",
    baselineDemeanor: "composed",
    deflections: [
      "Oh — I'm not sure about that one.",
      "I really couldn't say for certain.",
    ],
    demeanorImages: {
      composed: "/portraits/julia.jpg",
    },
    demeanorLines: {
      composed: "Chatty and a little distracted — she talks like someone glad for the company.",
    },
    topics: [
      {
        id: "what_heard",
        chipLabel: "What did you hear that night?",
        tone: "neutral",
        keywords: ["hear", "heard", "argument", "noise", "sound", "shouting", "yelling", "fighting", "scream", "through the wall"],
        stages: [
          {
            text: "Raised voices, more than once that night. Doors. The usual things you hear through a wall you shouldn't be able to hear through.",
            demeanor: "composed",
            addsBoardEntries: [
              { type: "claim", text: "Julia: heard multiple episodes of raised voices and doors that night.", source: "julia" },
            ],
          },
        ],
      },
      {
        id: "the_woman",
        chipLabel: "Did you see anyone leave?",
        tone: "neutral",
        keywords: ["see anyone", "leave", "woman", "coat", "midnight", "see", "describe", "what did you see", "saw", "exit", "walked out", "front door"],
        stages: [
          {
            text: "I saw a woman leaving, in a dark coat — around midnight, I think, give or take. She was holding something small, I couldn't tell you what. She looked back toward his door before she went. I couldn't see her face properly, the hallway light's been out for weeks.",
            demeanor: "composed",
            addsBoardEntries: [
              { type: "claim", text: "Julia: saw a woman in a dark coat leave “around midnight, give or take,” holding something small, face not clearly seen.", source: "julia", timestamp: "~midnight (imprecise)" },
            ],
          },
        ],
      },
      {
        id: "sure_about_time",
        chipLabel: "How sure are you about the time?",
        tone: "soft",
        keywords: ["sure", "certain", "exact time", "precise", "positive", "accurate", "clock", "really midnight", "how sure"],
        stages: [
          {
            text: "Not very, if I'm honest. I wasn't looking at a clock. “Around midnight” is the best I can give you — it could have been a bit before, a bit after. I wouldn't swear to the minute.",
            requiresWitnessStage: { witness: "julia", topic: "the_woman", minStage: 0 },
            demeanor: "composed",
            addsBoardEntries: [
              { type: "claim", text: "Julia, pressed: admits her “around midnight” sighting is an estimate, not a precise time.", source: "julia" },
            ],
          },
        ],
      },
    ],
  },
];

export const WITNESS_BY_ID: Record<string, WitnessConfig> = Object.fromEntries(
  WITNESSES.map((w) => [w.id, w])
);

export const EVIDENCE_BY_ID: Record<string, EvidenceItem> = Object.fromEntries(
  EVIDENCE.map((e) => [e.id, e])
);

/**
 * Cross-witness belief propagation: facts significant enough that relaying
 * them to another witness is authored to matter. Each `source` points at
 * the exact stage that makes the fact "known" — nothing here is a new flag
 * to keep in sync, it's derived from the same stage-reach state the rest
 * of the engine already tracks. A revelation with no authored `reactions`
 * entry on a given witness simply isn't offered for that pairing (see
 * WitnessChat's relay picker) rather than producing a blank/generic line.
 */
export const REVELATIONS: Record<RevelationId, RevelationDef> = {
  tom_returned: {
    id: "tom_returned",
    label: "Tom actually came back to the apartment that night.",
    source: { witness: "tom", topic: "after_that", minStage: 1 },
  },
  tom_confessed: {
    id: "tom_confessed",
    label: "Tom says the knife went into Daniel by accident, during a struggle.",
    source: { witness: "tom", topic: "the_knife", minStage: 1 },
  },
  sofia_visited: {
    id: "sofia_visited",
    label: "Sofia also went to the apartment that night, after Elena left.",
    source: { witness: "sofia", topic: "went_to_apartment", minStage: 1 },
  },
  elena_shoved: {
    id: "elena_shoved",
    label: "Elena admits she shoved Daniel during their argument.",
    source: { witness: "elena", topic: "argument", minStage: 1 },
  },
  daniel_lied_to_both: {
    id: "daniel_lied_to_both",
    label: "Daniel told his brother, a week before he died: “I've lied to both of them.”",
    source: { witness: "marco", topic: "the_lies", minStage: 0 },
  },
  sofia_contact_hidden: {
    id: "sofia_contact_hidden",
    label: "Sofia initially denied any contact with Daniel after his 23:06 text — phone records say otherwise.",
    source: { witness: "sofia", topic: "contact_after_text", minStage: 1 },
  },
};
